# Pull secret for private repository
imagePullSecrets:
  web: regcred-web
  api: regcred-api

# Configuration for book-review-api
api:
  replicaCount: 2
  image:
    repository: 261922930011.dkr.ecr.us-east-1.amazonaws.com/book-review-api
    tag: de2d069
  containerPort: 8000
  servicePort: 8000

# Configuration for book-review-web
web:
  replicaCount: 2
  image:
    repository: 261922930011.dkr.ecr.us-east-1.amazonaws.com/book-review-web
    tag: de2d069
  containerPort: 3000
  servicePort: 3000
