name: Build Docker Images

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "deploy/**"

jobs:
  pr_build:
    name: Build Docker Images
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          make build-api build-web
