on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_job:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build web
        run: make build-web

      - name: Build api
        run: make build-api
